apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-deploy
spec:
  steps:
    # - name: build
    #   image: 'docker:24.0.5'
    #   env:
    #     - name: DOCKER_HOST
    #       value: 'tcp://localhost:2376'
    #     - name: DOCKER_TLS_VERIFY
    #       value: '1'
    #     - name: DOCKER_CERT_PATH
    #       value: /certs/client
    #   script: |
    #     docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    #     export SHORT_SHA=${SHA:0:7}
    #     docker build -t $CI_REGISTRY_IMAGE:$SHORT_SHA .
    #     docker push $CI_REGISTRY_IMAGE:$SHORT_SHA
    #   volumeMounts:
    #     - mountPath: /certs/client
    #       name: dind-certs
    - name: deploy
      image: 'google/cloud-sdk:latest'
      script: |
        export SHORT_SHA=${SHA:0:7}
        echo "SERVICE_ACCOUNT: $SERVICE_ACCOUNT"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "COMPUTE_ZONE: $COMPUTE_ZONE"
        echo "CLUSTER_NAME: $CLUSTER_NAME"
        echo "DEPLOYMENT_NAME: $DEPLOYMENT_NAME"
  sidecars:
    - image: 'docker:24.0.5-dind'
      name: server
      resources:
        requests:
          memory: 2Gi
          cpu: 2000m
        limits:
          memory: 2Gi
          cpu: 2000m
      args:
        - '--storage-driver=vfs'
        - '--userland-proxy=false'
        - '--debug'
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
      readinessProbe:
        periodSeconds: 1
        exec:
          command:
            - ls
            - /certs/client/ca.pem
  volumes:
    - name: dind-certs
      emptyDir: {}

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: run-build-deploy
      taskRef:
        name: build-deploy

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run
spec:
  pipelineRef:
    name: pipeline

