on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI_REGISTRY_USER: "dockerusername"
  CI_REGISTRY_PASSWORD: "dockerpassowrd"
  CI_REGISTRY: "path to registry"
  CI_REGISTRY_IMAGE: "gh-trends"

jobs:
  build_job:
    name: Build Job
    runs-on: docker:latest
    steps:
      - name: build
        run: 
          - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
          - docker build -t $CI_REGISTRY_IMAGE .
          - docker push $CI_REGISTRY_IMAGE
  deploy_job:
    name: Deploy Job
    runs-on: google/cloud-sdk:latest
    steps:
      - name: deploy
        run:
          - echo $SERVICE_ACCOUNT > /tmp/service_account.json
          - gcloud auth activate-service-account --key-file /tmp/service_account.json
          - gcloud config set project $PROJECT_ID
          - gcloud config set compute/zone $COMPUTE_ZONE
          - gcloud container clusters get-credentials $CLUSTER_NAME
          - kubectl apply -f deployment.yaml
          - kubectl apply -f service.yaml
          - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$CI_REGISTRY_IMAGE:latest
