stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

deploy-job:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project $PROJECT_ID
    - gcloud config set compute/zone $COMPUTE_ZONE
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml
    - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
