apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-trends-k8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gh-trends
  template:
    metadata:
      labels:
        app: gh-trends
    spec:
      containers:
        - name: gh-trends-container
          image: registry.gitlab.com/ebenezerdon/gh-trends:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
            requests:
              cpu: '0.1'
              memory: '256Mi'
