apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000 # target app port, specified in Dockerfile
  selector:
    app: gh-trends
